# Generated by Django 5.0 on 2024-08-22 14:45

import autoslug.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('account_type', models.CharField(choices=[('Asset', 'Asset'), ('Liability', 'Liability'), ('Equity', 'Equity'), ('Revenue', 'Revenue'), ('Expense', 'Expense'), ('Gain', 'Gain'), ('Loss', 'Loss')], max_length=50)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GatePass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.CharField(max_length=255)),
                ('dispatch_for', models.CharField(max_length=255)),
                ('name_of_site', models.CharField(max_length=255)),
                ('person_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('returnable', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=255)),
                ('product_sale_price', models.CharField(max_length=255)),
                ('product_quantity', models.CharField(max_length=255)),
                ('product_status', models.CharField(choices=[('Atcive', 'Active'), ('Inactive', 'Inactive')], max_length=50)),
                ('is_deleted', models.BooleanField(default=False)),
                ('product_slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='productname', unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='home.category')),
            ],
        ),
        migrations.CreateModel(
            name='GatePassProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('remarks', models.CharField(max_length=255, null=True)),
                ('gatepass', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='home.gatepass')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='home.product')),
            ],
        ),
        migrations.AddField(
            model_name='gatepass',
            name='products',
            field=models.ManyToManyField(through='home.GatePassProduct', to='home.product'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_deleted', models.BooleanField(default=False)),
                ('credit_account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='credit_transactions', to='home.account')),
                ('debit_account', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='debit_transactions', to='home.account')),
            ],
        ),
    ]
