# Generated by Django 5.0 on 2024-09-13 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_reciept_product',
            name='salereceipt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='home.sales_reciept'),
        ),
    ]
