# Generated by Django 5.0 on 2024-09-13 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_sales_reciept_product_salereceipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales_reciept',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sales_reciept_product',
            name='salereceipt',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='home.sales_reciept'),
            preserve_default=False,
        ),
    ]
