# Generated by Django 5.0 on 2024-08-22 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_product_product_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_sale_price',
        ),
    ]
