# Generated by Django 5.0 on 2024-09-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_sales_reciept_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatepass',
            name='returnable',
            field=models.BooleanField(null=True),
        ),
    ]
