# Generated by Django 5.0 on 2024-09-13 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_gatepass_returnable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sales_Reciept_Product',
            new_name='Sales_Receipt_Product',
        ),
        migrations.CreateModel(
            name='Sales_Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('customer_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=12)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(through='home.Sales_Receipt_Product', to='home.product')),
            ],
        ),
        migrations.AlterField(
            model_name='sales_receipt_product',
            name='salereceipt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='home.sales_receipt'),
        ),
        migrations.DeleteModel(
            name='Sales_Reciept',
        ),
    ]
