# Generated by Django 5.0 on 2024-08-23 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_product_product_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepassproduct',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='home.unit'),
            preserve_default=False,
        ),
    ]
