# Generated by Django 5.0 on 2024-08-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_gatepassproduct_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_weight',
            field=models.CharField(default=5, max_length=255),
            preserve_default=False,
        ),
    ]
