# Generated by Django 5.0 on 2024-09-13 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_sales_reciept_product_sales_receipt_product_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'permissions': [('view_dashboard', 'Can view dashboard'), ('view_balance_sheet', 'Can view balance sheet')]},
        ),
    ]
