# Generated by Django 5.0 on 2024-08-23 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_product_product_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gatepassproduct',
            name='unit',
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='home.unit'),
            preserve_default=False,
        ),
    ]
