# Generated by Django 5.0 on 2024-08-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_remove_gatepassproduct_unit_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pro_img',
            field=models.ImageField(null=True, upload_to='uploaded/products/'),
        ),
    ]
