# Generated by Django 5.0 on 2024-08-30 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_product_pro_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales_Reciept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('cutomer_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Sales_Reciept_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('gatepass', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='home.sales_reciept')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='home.product')),
            ],
        ),
        migrations.AddField(
            model_name='sales_reciept',
            name='products',
            field=models.ManyToManyField(through='home.Sales_Reciept_Product', to='home.product'),
        ),
    ]
