# Generated by Django 5.0 on 2024-08-30 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_slaericeipt_sales_reciept_product_salericeipt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales_reciept_product',
            old_name='salericeipt',
            new_name='salereceipt',
        ),
    ]
