# Generated by Django 5.0 on 2024-08-30 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_salericeipt_sales_reciept_product_salereceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_reciept_product',
            name='amount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sales_reciept_product',
            name='unit_price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='sales_reciept_product',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
