# Generated by Django 5.0 on 2024-10-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_quantity',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
