# Generated by Django 5.0 on 2024-08-30 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_sales_reciept_product_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales_reciept',
            old_name='cutomer_name',
            new_name='customer_name',
        ),
        migrations.AlterField(
            model_name='sales_reciept',
            name='phone_number',
            field=models.CharField(max_length=12),
        ),
    ]
