# Generated by Django 5.0 on 2024-10-06 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_product_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='home.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='product_prices', to='home.product')),
            ],
            options={
                'unique_together': {('product', 'customer')},
            },
        ),
    ]
