# Generated by Django 5.0 on 2024-08-30 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_rename_cutomer_name_sales_reciept_customer_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_reciept',
            name='created_by',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
