# Generated by Django 5.0 on 2024-10-06 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_price',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='product_price', to='home.product'),
        ),
    ]
