# Generated by Django 5.0 on 2024-10-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_product_price_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_price',
            name='is_deleted',
            field=models.BooleanField(null=True),
        ),
    ]
