# Generated by Django 5.0 on 2024-08-31 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_sales_reciept_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepass',
            name='driver_phone_number',
            field=models.CharField(default=1234567890, max_length=20),
            preserve_default=False,
        ),
    ]
