# Generated by Django 5.0 on 2024-10-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_product_price_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_price',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
