# Generated by Django 5.0 on 2024-10-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_alter_product_price_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_price',
            name='price',
            field=models.FloatField(),
        ),
    ]
