# Generated by Django 5.0 on 2024-11-17 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_product_price_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='cheque_amount',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cheque',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
