# Generated by Django 5.0 on 2024-09-04 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_suppliers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliers',
            name='contact',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
