# Generated by Django 5.0 on 2024-11-17 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_cheque_cheque_amount_cheque_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cheque',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='home.cheque'),
        ),
    ]
