# Generated by Django 5.0 on 2024-09-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_suppliers_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('adress', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=12, null=True, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='suppliers',
            name='contact',
            field=models.CharField(max_length=12, null=True, unique=True),
        ),
    ]
