# Generated by Django 5.1.3 on 2024-11-18 04:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_account_customer_alter_account_employee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 18, 9, 34, 55, 63430)),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('Asset', 'Asset'), ('Liability', 'Liability'), ('Equity', 'Equity'), ('Revenue', 'Revenue'), ('Expense', 'Expense'), ('Gain', 'Gain'), ('Loss', 'Loss'), ('Commitment', 'Commitment')], max_length=50),
        ),
    ]
