# Generated by Django 5.0 on 2024-09-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_cheque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='bank_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='cheque_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
