# Generated by Django 5.0 on 2024-11-23 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_account_date_alter_account_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_receipt',
            name='make_transaction',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('Asset', 'Asset'), ('Liability', 'Liability'), ('Equity', 'Equity'), ('Revenue', 'Revenue'), ('Expense', 'Expense'), ('Gain', 'Gain'), ('Loss', 'Loss'), ('Commitment', 'Commitment'), ('Commitment_Received', 'Commitment_Received')], max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 23, 22, 36, 17, 488284)),
        ),
    ]
