# Generated by Django 5.1.3 on 2024-11-24 12:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_sales_receipt_make_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 24, 17, 20, 7, 860263)),
        ),
        migrations.AlterField(
            model_name='sales_receipt',
            name='customer_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='home.customer'),
        ),
    ]
