# Generated by Django 5.1.3 on 2024-11-24 12:26

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_alter_account_date_alter_sales_receipt_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 24, 17, 26, 1, 562952)),
        ),
        migrations.AlterField(
            model_name='sales_receipt',
            name='customer_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='home.customer'),
        ),
    ]
