# Generated by Django 5.0 on 2024-11-30 13:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_alter_account_date_alter_sales_receipt_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales_receipt',
            name='customer',
            field=models.CharField(blank=True, max_length=220, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 30, 18, 48, 39, 599565)),
        ),
    ]
